### ISSUE TITLE
Markdown alerts do not seem to display background color

### ISSUE THREAD

**Issue by Nadine2016** [colinwilson/lotusdocs#49]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for support

### Describe the bug

HTML alerts display with a background color. 

Example code: 
```
{{< alert icon="🍅" context="success" text="HTML alert" />}}
```

Displays as: 
<img width="1057" alt="image" src="https://github.com/colinwilson/lotusdocs/assets/17709352/8b9ad9e8-e433-46db-ad12-a9257df33a5c">

However, when I create a markdown alert, it does not seem to come up with a background color. 

Example code: 
```
{{% alert icon="🍅" context="success" %}} 
Markdown 
{{% /alert %}}
```

Displays as: 
<img width="403" alt="image" src="https://github.com/colinwilson/lotusdocs/assets/17709352/6a7feeff-5d6e-4776-98bb-032c55397552">

I tried the markdown example with the cart icon in your doc as well, but it seems to not show a background color either. 

### Expected behavior

Have markdown alerts display the selected background color. 

### Environment

```markdown
- OS: macOS
- Browser: Chrome
- Browser Version: 116
```

**Comment by colinwilson** [comment]
Having trouble replicating this. Your example:
```
{{% alert icon="🍅" context="success" %}} 
Markdown 
{{% /alert %}}
```
renders as below for me *(Chrome/FireFox on Windows/MacOS)*:

![2023-08-31 01_56_45-Window](https://github.com/colinwilson/lotusdocs/assets/12916656/e87cc030-83f4-47ec-8654-f2410493441b)

Do you see any warnings, errors, 404's in Chrome's dev tools? Is the alert code nested inside another Shortcode?

**Comment by Nadine2016** [comment]
@colinwilson It looks like that the markdown alert is not assigned a css class, but HTML alerts are assigned one. 

This is the example for the markdown alert
<img width="479" alt="image" src="https://github.com/colinwilson/lotusdocs/assets/17709352/a1aae54d-89d2-4b4d-a788-9884f7c0128b">

And this is the HTML alert output: 
<img width="658" alt="image" src="https://github.com/colinwilson/lotusdocs/assets/17709352/9080518c-750d-4f15-8d14-79bf473ee41a">


This shortcode is not used within a shortcode. It is placed right underneath the heading. I was checking the network tab in the Chrome developer tools, but I cannot see any errors. I am using Hugo 117 to build my site. I am not sure if it could be related to the Hugo version?

**Comment by colinwilson** [comment]
Ah, Apologies!

This is due to a lack of documentation on my part! 

The `<!-- raw HTML omitted -->` in your screenshot indicates a missing (required) parameter in your `hugo.toml` config.

Set `unsafe = true` under `[markup.goldmark.renderer]` in your `hugo.toml` config like below:

```
[markup.goldmark.renderer]
    unsafe = true
```
- Without the `unsafe = true` setting, raw HTML in a Goldmark-flavored Markdown source file will be replaced with `<!-- raw HTML omitted -->` in the markdownified⁠ destination file. This was introduced in [Hugo v0.60.0](https://github.com/gohugoio/hugo/releases/tag/v0.60.0) when [Goldmark](https://github.com/yuin/goldmark/) became the default library used for Markdown in Hugo. The markdown (`%`) alert shortcode won't render properly without this setting.

I'll document this **ASAP** and update the example `hugo.toml` in the repo.

**Comment by Nadine2016** [comment]
ah awesome! this worked like a charm. Thank you so much! :)

**Comment by colinwilson** [comment]
You're welcome. 👍

I'll close this once I've updated the docs and repo to reflect the config requirements for the theme.
